name: GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: |
        git config --global user.email "aditya.srinivasan11@gmail.com"
        git config --global user.name "adisrini"

    - run: yarn deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        CI: true